web:
  build: apache
  links:
    - db
    - mail
  ports:
    - "80:80"
    - "8000:8000"
  volumes:
    - ./www:/var/www/html
mail:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
db:
    build: mysql
    ports:
      - "3306:3306"
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8080:80"
    links:
      - db
